package com.skillup.skillup.features.coordination.service;
import com.skillup.skillup.common.exception.*; import com.skillup.skillup.common.security.CurrentUserService; import com.skillup.skillup.features.coordination.dto.request.*; import com.skillup.skillup.features.coordination.dto.response.*; import com.skillup.skillup.features.coordination.entity.*; import com.skillup.skillup.features.coordination.repository.CoordinationRequestRepository; import com.skillup.skillup.features.execution.repository.ActionItemRepository;
import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import java.time.LocalDateTime;
@Service
public class CoordinationRequestService {
 private final CoordinationRequestRepository repo; private final ActionItemRepository actionItemRepo; private final CurrentUserService user;
 public CoordinationRequestService(CoordinationRequestRepository r,ActionItemRepository a,CurrentUserService u){repo=r;actionItemRepo=a;user=u;}
 public PageCoordinationRequestResponse list(int page,int limit,String status,Long actionItemId){validatePage(page,limit);CoordinationRequestStatus s=parseStatus(status);Page<CoordinationRequest> result=repo.findRequests(s==null?null:s.name(),actionItemId,PageRequest.of(page-1,limit));return new PageCoordinationRequestResponse(result.getContent().stream().map(this::toResponse).toList(),page,limit,result.getTotalElements(),result.getTotalPages());}
 public CoordinationRequestResponse create(RequestCreateRequest req){if(!actionItemRepo.existsById(req.getActionItemId()))throw new ResourceNotFoundException("Action item not found with id: "+req.getActionItemId());CoordinationRequest r=new CoordinationRequest();r.setActionItemId(req.getActionItemId());r.setRaisedBy(user.getCurrentUserId());r.setRequestType(req.getRequestType());r.setDescription(req.getDescription());r.setStatus(CoordinationRequestStatus.RAISED);r.setCreatedAt(LocalDateTime.now());r.setUpdatedAt(LocalDateTime.now());return toResponse(repo.save(r));}
 public CoordinationRequestResponse update(Long id,RequestUpdateRequest req){CoordinationRequest r=find(id);CoordinationRequestStatus s=parseStatus(req.getStatus());r.setAssignedTo(req.getAssignedTo());r.setStatus(s);r.setDescription(req.getDescription());r.setUpdatedAt(LocalDateTime.now());return toResponse(repo.save(r));}
 private CoordinationRequest find(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Request not found with id: "+id));}
 private CoordinationRequestResponse toResponse(CoordinationRequest r){return new CoordinationRequestResponse(r.getId(),r.getActionItemId(),r.getRaisedBy(),r.getAssignedTo(),r.getRequestType(),r.getDescription(),r.getStatus(),r.getCreatedAt(),r.getUpdatedAt());}
 private void validatePage(int p,int l){if(p<1)throw new BadRequestException("Page must be greater than or equal to 1");if(l<1||l>100)throw new BadRequestException("Limit must be between 1 and 100");}
 private CoordinationRequestStatus parseStatus(String s){if(s==null||s.isBlank())return null;try{return CoordinationRequestStatus.valueOf(s.toUpperCase());}catch(Exception e){throw new BadRequestException("Invalid request status: "+s);}}
}
